### ISSUE TITLE
Where can l define the `input file path` and the `output file path`?

### ISSUE THREAD

**Issue by mendax1234** [3ru/gpt-translate#11]
<img width="418" alt="image" src="https://github.com/3ru/gpt-translate/assets/62934294/c2e4dae7-a1a9-4c89-b326-77843f9b028e">
l am curious about where l can define the `input file path and the `output file path`. Besides, if l want to use this Action, should I copy the minimal example directly to my gpt-translate.yml?

**Comment by 3ru** [comment]
This Action is initiated by you or someone else with **Write** access to the repository by entering a command in response to an issue comment or PR comment.

Note that it is a comment, as it does not make sense to enter a command in the title of an issue, etc.

> Besides, if l want to use this Action, should I copy the minimal example directly to my gpt-translate.yml?

Yes! The OpenAI API side is sometimes unstable, but I think it works correctly.

**Comment by 3ru** [comment]
@mendax1234 

like this 👇

```
/gt README.md README.zh-tw.md traditional-chinese
```

**Comment by mendax1234** [comment]
> @mendax1234
> 
> like this 👇
> 
> ```
> /gt README.md README.zh-tw.md traditional-chinese
> ```



> @mendax1234
> 
> like this 👇
> 
> ```
> /gt README.md README.zh-tw.md traditional-chinese
> ```

Thanks! So, it doesn't matter what the title of the issue is.

**Comment by 3ru** [comment]
> Thanks! So, it doesn't matter what the title of the issue is.

Yes!
