### ISSUE TITLE
Automated usage after every commit

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#14]
Hi, I tried to integrate your tool in my workflow with the intention that after every commit from GitBook it translates automatically every changed file into specified languages.

Unfortunately I get an error message because the path to push the issue-comment was not found.
Maybe you can adjust that to make it usable also after every commit?

thanks in advance :)

**Comment by 3ru** [comment]
@makeitr3al 
Thanks for using it, I have added some experimental features that would accomplish your requirements.
Try it out as I will create a PR against your repository.
Also, if you encounter any problems, please feel free to contact us via issues, discussions, etc.

**Comment by makeitr3al** [comment]
Very nice!
Tested it already, works pretty fine so far.
But I guess I'll change the trigger that it only runs when original content has changed (means content in 'EN/').

Thank you also for the feature to translate the whole directory! I guess this command needs to be triggered also with a issue-comment right?

Cheers

**Comment by 3ru** [comment]
@makeitr3al 
I am glad the good news worked :))

I think the following change will work to make it only when there is a change in `EN/`.

```yml
    echo "files=$(git diff --name-only HEAD^ HEAD | grep '^EN/.*\.md$' | tr '\n' ' ')" >> $GITHUB_OUTPUT
```
Extract only .md files that begin with EN/ with a regular expression.

**Comment by makeitr3al** [comment]
Nice! Going to try that.

Does your request to ChatGPT reviews his received translations for mistakes in Grammar?

**Comment by 3ru** [comment]
@makeitr3al 

Since the text is generated with a high degree of accuracy from the beginning, I have not included a process to review the grammar in particular.

**Comment by 3ru** [comment]
Resolved.
