### ISSUE TITLE
Request failed with status code 503

### ISSUE THREAD

**Issue by 3ru** [3ru/gpt-translate#18]
Probably there is a limit of concurrent execution on the OpenAI side, and if it is exceeded, an error will occur?

Log: https://github.com/makeitr3al/XBorg/actions/runs/5499666985/jobs/10022031475

A possible solution is a serial execution, but I would like more official information to perform the translation most efficiently.

**Comment by makeitr3al** [comment]
I guess it doesn't worked with the grep 'EN/*.md'
I had to revert that to '/*.md'

**Comment by 3ru** [comment]
GitHub Actions is pay-as-you-go based on the time used, and I would like to maintain the current parallelism as much as possible to shorten the execution time.
