### ISSUE TITLE
token limit exceeded

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#19]
Hi :)

I made a lot changes in original content. Then I got this issue:

Error: Request failed with status code 503
Error: If the status code is 400, the file exceeds 16,000 tokens without line breaks. 

Is there a limit of characters to translate? Could you split them by files or sentences?

**Comment by 3ru** [comment]
@makeitr3al 

This is a 503 error, so it is a separate issue from token overage.
#18, the problem is that there are many translated files.
This problem occurs irregularly on the OpenAI API side and cannot currently be solved essentially.

**Comment by makeitr3al** [comment]
it's not possible to split the request, to ensure not to reach the limit?

**Comment by 3ru** [comment]
@makeitr3al 
Originally, the translation was divided into smaller pieces, but this increased the waiting time until the translation was completed, so I decided to use parallel processing.

Does this 503 error occur quite often?

**Comment by 3ru** [comment]
@makeitr3al 
I checked[ your log](https://github.com/makeitr3al/XBorg/actions/runs/5517562573/jobs/10060346779) and you are trying to translate 126 files. Such a large change may not be able to be handled in its current state. If this happens more often, please let me know again.

**Comment by makeitr3al** [comment]
yes indeed, there were a lot files. Alright I'll keep having an eye on that.
Closing this issue for now.
