### ISSUE TITLE
page-structure not inherited

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#20]
do you have any idea how to inherit the page-tree when translating the content?

I tried to translate the whole directory with an issue-comment but it doesn't inherit the whole path from original path.

**Comment by 3ru** [comment]
@makeitr3al 
I don't understand your problem.
Please tell me the command you tried to execute, the expected result, and the actual result.

**Comment by 3ru** [comment]
@makeitr3al 

Understood.
I see that your preference here is to save it in `DE/01-or-core/`.

Currently, directory paths cannot be inherited, so I will add a feature to allow this.

**Comment by makeitr3al** [comment]
@3ru 
yes exactly. But there's no preference, it's just an example to show you what I like to do.

Phantastic! Thanks a lot.

**Comment by 3ru** [comment]
@makeitr3al 

I have included an experimental release that allows directory inheritance.
I created a PR, please try it!

**Comment by makeitr3al** [comment]
@3ru 
Thanks a lot! Will try it

**Comment by makeitr3al** [comment]
@3ru 
It seems to work well. I now delete all files that are made in the wrong directory, then all repositories are fine.
Can I use the same changes in the .yml file for translation by issue-comment?

**Comment by 3ru** [comment]
@makeitr3al 
Currently, the command does not allow directory inheritance.
Reflecting the same changes in yml is fine, but ineffective.

**Comment by makeitr3al** [comment]
@3ru 
Sometimes when files or directories have been deleted it occurs an error because of missing files. Also when I recreate the exact same file on the exact same position I don't get the job rerunned successfully.

And a feature to translate the whole directory by an issue comment would be phantastic (for example to add a new language).

all other things are working very good! Much apreciated to have you! :)

**Comment by 3ru** [comment]
@makeitr3al 
Thanks for the feedback!

It may take a little time due to my hospitalization schedule, but I will investigate and make improvements:)

**Comment by makeitr3al** [comment]
@3ru 
you're welcome!

Oh I hope nothing serious... get well soon then!
