### ISSUE TITLE
The path and syntax of the file will be made to translate

### ISSUE THREAD

**Issue by makeitr3al** [3ru/gpt-translate#26]
Hi @3ru 
Translation normally uses the same directory as given. But when translating into Dutch, file-paths getting changed and I have no idea why :)

Referring to PR: gt-2e2a08d0-98f0-4fc6-86dd-b88c2d0738ea

**Comment by makeitr3al** [comment]
https://github.com/makeitr3al/XBorg/pull/96#issue-1851170949

**Comment by 3ru** [comment]
@makeitr3al 
Did you run this with a command?
Could you be a little more specific about what environment you are in and what the problem is?

**Comment by makeitr3al** [comment]
@3ru 
Yes you're right sorry. I did that by an issue-comment with the command "/gt EN/*.md DT/*.md Dutch"

What you mean by environment?

**Comment by 3ru** [comment]
@makeitr3al 
I still don't understand your problem.
`EN/*.md DT/*.md' If you run a command like this, the files under the EN directory will be translated into German.

There are two files under the EN directory in your repository, `README.md` and `SUMMARY.md`, which seem to output to the appropriate paths.

**Comment by makeitr3al** [comment]
Hi @3ru 
First, I'd like to say thank you for implementing the feature to select the GPT-model :)

To make process in this issue here is a screenshot of the problem. The difference in the Dutch language-translation is, that also file-paths gets translated. In all the other languages that doesn't happen. The file-path remains, as it is.

![image](https://github.com/3ru/gpt-translate/assets/132067780/6aac02bc-1c85-4cb3-b0f7-1bb77b5d7baa)

**Comment by 3ru** [comment]
@makeitr3al 
Understood.
It is a bit difficult to solve this completely, so I will try to verify if I can't take care of this in the prompt.

**Comment by makeitr3al** [comment]
Hi @3ru long time no see. Hope you're good?
This issue unfortunately happens again. It's just happening for a few languages. That makes it a bit strange...
Currently I've faced that issue for: Dutch, French and Albanian.

As a recap: The problem is, that ChatGPT translates also the path including the filename. Done that, the file won't get found and the SUMMARY.md points to a non existing path/file.
