### ISSUE TITLE
error 429

### ISSUE THREAD

**Issue by yuessir** [3ru/gpt-translate#48]
### To Reproduce

not sure why always happened 

### Current vs. Expected behavior

2/3/2024, 2:33:33 PM Start translating with gpt-4...
Error: Error: Request failed with status code 429
Notice: If the status code is 400, the file exceeds token limit without line breaks. 
Please open one line as appropriate.
Notice: If the status code is 404, you do not have right access to the model.

### Provide environment information

```yml
using gpt-4
```
after topping up to my openapi , the situation still happened 

### How do you run translations?

By Command

**Comment by 3ru** [comment]
Perhaps the reason is that OpenAI frequently changes the token limits by model.
Can you try again with one of the models `gpt-4-0125-preview`,`gpt-4-turbo-preview`,`gpt-4-1106-preview`,`gpt-4-vision-preview`?

**Comment by yuessir** [comment]
> @yuessir 
> 
> The reason may be that OpenAI frequently changes the token limits by model.
> 
> Can you try again with one of the models `gpt-4-0125-preview`,`gpt-4-turbo-preview`,`gpt-4-1106-preview`,`gpt-4-vision-preview`?
> 
> 


I have used the `gpt-4-0125-preview`  model. Now it seems that there is no error 429. But this model did not translate all the documents I entered. It only translated less than 10% and then proceeded with the PR.

**Comment by yuessir** [comment]
> > @yuessir
> > The reason may be that OpenAI frequently changes the token limits by model.
> > Can you try again with one of the models `gpt-4-0125-preview`,`gpt-4-turbo-preview`,`gpt-4-1106-preview`,`gpt-4-vision-preview`?
> 
> I have used the `gpt-4-0125-preview` model. Now it seems that there is no error 429. But this model did not translate all the documents I entered. It only translated less than 10% and then proceeded with the PR.

it seems that was the unstable case, now it is fine
