### ISSUE TITLE
Error: Request failed with status code 429

### ISSUE THREAD

**Issue by bryanpaget** [3ru/gpt-translate#6]
This is a cool action! I've tried using it but I'm getting a `429` error.

This is the PR I'm testing the action with: https://github.com/bryanpaget/machine-translated-documentation/pull/1

Here is a screenshot:
![image](https://user-images.githubusercontent.com/8212170/236503427-5f4c5b51-e832-475c-b8d8-a469630426cc.png)

I've checked my OpenAI account and nothing seems to be wrong with my account or the number of API requests that I have. I even made a new API key just for the action.

**Comment by addisonschultz** [comment]
Hey @bryanpaget @3ru! Great work on this indeed, it's very useful! 

I've forked this repo to try and implement support for multiple languages, and mapping over directories - but I'm also running into this rate limiting error (`429`) 

Did you run into this when you were developing the original action?

**Comment by 3ru** [comment]
Sorry for the late reply. I will investigate immediately!

**Comment by 3ru** [comment]
I was able to reproduce the 401 error when I ran it with the API Key of the free plan. (Maybe there was a free grant until May, but it has been gone since then?)

However, I could not reproduce the error with a key that has been billed with billing settings.

Please check if your API Key can be used to make a normal request.

**Comment by cubxxw** [comment]
@3ru oh, there is no way to implement the free plan token

**Comment by 3ru** [comment]
@cubxxw Apparently, the Open AI API is no longer available for free.

![image](https://github.com/3ru/gpt-translate/assets/69892552/b72d69ed-8b34-459d-b542-e11e47223724)

**Comment by 3ru** [comment]
Added note that the free API Key is currently not available on the openai side.
