### ISSUE TITLE
Error: Request failed with status code 502

### ISSUE THREAD

**Issue by yangtzech** [3ru/gpt-translate#9]
Thanks for your wonderful action! I just tried it, but got `Error: Request failed with status code 502`.

I have added the billing information to get a paid account. And what I used to trigger this action is: `/gpt-translate README.md zh-CN/README.md simplified-chinese`.

![image](https://github.com/3ru/gpt-translate/assets/41911522/38c1488d-fe3c-42c9-9f20-1432fd83b504)

**Comment by yangtzech** [comment]
I searched this error code and found it seems to be the server problem of openai. It happens occasionally. So I tried this command again days later and no error occured.

**Comment by 3ru** [comment]
>I searched this error code and found it seems to be the server problem of openai. It happens occasionally. So I tried this command again days later and no error occurred.

I see, I hope it works okay! 😸
